app/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from .models import Post, User, Comments, Likes, Saved
from . import db

# import json
# from datetime import datetime

views = Blueprint('views', __name__)


@views.route('/')
@views.route('/home')
@login_required
def home():
    posts = Post.query.all()
    comments = Comments.query.all()
    return render_template('home.html', user=current_user, posts=posts, comments=comments)


@views.route('/add_post', methods=['POST', 'GET'])
@login_required
def add_post():
    if request.method == 'POST':
        post = request.form.get('post')
        if len(post) < 1:
            flash('Post is too short!')
        else:
            new_post = Post(post=post, author=current_user.id, edit=False)
            db.session.add(new_post)
            db.session.commit()
            return redirect(url_for('views.home'))

    return render_template('home.html', user=current_user)


@views.route('/delete_post/<id>')
@login_required
def delete_post(id):
    post = Post.query.filter_by(id=id).first()
    if not post:
        flash('Post does not exist', category='error')
    elif current_user.id != post.author:
        flash('You dont have permission', category='error')
    else:
        db.session.delete(post)
        db.session.commit()
        flash('Post deleted', category='success')

    return redirect(url_for('views.home'))


@views.route('/user_posts/<username>')
@login_required
def user_posts(username):
    user = User.query.filter_by(username=username).first()
    if not user:
        flash('User does not exist', category='error')
        return redirect(url_for('views.home'))
    else:
        # posts = Post.query.filter_by(author=user.id).all() jeden sposób
        posts = user.posts
        return render_template('user_posts.html', user=user, posts=posts, title=f"{user.username}'s posts")


@views.route('/add_comment/<post_id>', methods=['POST'])
@login_required
def add_comment(post_id):
    comment = request.form.get('comment')
    post = Post.query.filter_by(id=post_id)
    if len(comment) < 1:
        flash('Comment is too short!', category='error')
    else:
        if post:
            new_comment = Comments(comment=comment, author=current_user.id, post_id=post_id, edit_switch=False)
            db.session.add(new_comment)
            db.session.commit()
        else:
            flash('Post does not exist', category='error')
    return redirect(url_for('views.home'))


@views.route('/delete_comment/<int:comment_id>/<int:post_id>')
@login_required
def delete_comment(comment_id, post_id):
    comment = Comments.query.filter_by(id=comment_id, post_id=post_id).first()
    if comment.author != current_user.id:  # or carrent_user.id != comment.post.author
        flash('You dont have permission')
    else:
        db.session.delete(comment)
        db.session.commit()
    return redirect(url_for('views.home'))


@views.route('/like_post/<post_id>')
@login_required
def like_post(post_id):
    like = Likes.query.filter_by(post_id=post_id, author=current_user.id).first()
    post = Post.query.filter_by(id=post_id).first()
    if not post:
        flash('This post does not exist')
    elif like:
        db.session.delete(like)
        db.session.commit()
        return redirect(url_for('views.home'))
    else:
        like = Likes(post_id=post_id, author=current_user.id)
        db.session.add(like)
        db.session.commit()
        return redirect(url_for('views.home'))

@views.route('/edit/<post_id>', methods=['POST'])
@login_required
def edit(post_id):
    post = Post.query.filter_by(id=post_id).first()
    if not post:
        flash('Post does not exist')
    elif post.author == current_user.id:
        post.edit = not post.edit
        db.session.commit()
        if post.edit:
            flash('Post has been edited', category="success")
    return redirect(url_for('views.home'))


@views.route('/edit_post/<post_id>', methods=['POST'])
@login_required
def edit_post(post_id):
    post = Post.query.filter_by(id=post_id).first()
    if not post:
        return jsonify({'success': False, 'message': 'This post does not exist'})
    edit_post = request.form['post']
    post.edit = False
    post.post = edit_post
    db.session.commit()
    return redirect(url_for('views.home'))


@views.route('/edit_switch/<comment_id>', methods=['POST'])
@login_required
def edit_switch(comment_id):
    comment = Comments.query.filter_by(id=comment_id).first()
    if not comment:
        flash('Comment does not exist')
    elif comment.author == current_user.id:
        comment.edit_switch = not comment.edit_switch
        db.session.commit()
        if comment.edit_switch:
            flash('Comment has been edited', category="success")
    return redirect(url_for('views.home'))


@views.route('/edit_comment/<comment_id>', methods=['POST'])
@login_required
def edit_comment(comment_id):
    comment = Comments.query.filter_by(id=comment_id).first()
    if not comment:
        return jsonify({'success': False, 'message': 'This comment does not exist'})
    edit_comment = request.form['comment']
    comment.edit_switch = False
    comment.comment = edit_comment
    db.session.commit()
    return redirect(url_for('views.home'))

@views.route('/search')
@login_required
def search():
    search_item = request.args.get('search')
    all_posts = Post.query.all()
    findings = []
    for post in all_posts:
        post_text = post.post
        lower_search_item = str(search_item).lower()
        if lower_search_item in post_text:
            findings.append(post)
    return render_template('user_posts.html', posts=findings, user=current_user, title=f"posts containing word: {search_item} ")


@views.route('/show_saved')
@login_required
def show_saved():
    saved_posts = current_user.saved
    return render_template('user_posts.html', posts=saved_posts, user=current_user, title=f"Your saved posts")


@views.route('/saved/<post_id>')
@login_required
def saved(post_id):
    post = Post.query.filter_by(id=post_id).first()
    user = User.query.filter_by(id=current_user.id).first()
    if post not in user.saved:
        user.saved.append(post)
        db.session.commit()
    else:
        user.saved.remove(post)
        db.session.commit()
    return redirect(url_for('views.home'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
            crossorigin="anonymous"
    />
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
    />
    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    {% if user.is_authenticated %}
    <div class="container-fluid">
        <a class="navbar-brand" id="home" href="/">
            <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="grey" class="bi bi-house-heart"
                 viewBox="0 0 16 16">
                <path d="M8 6.982C9.664 5.309 13.825 8.236 8 12 2.175 8.236 6.336 5.309 8 6.982Z"/>
                <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.707L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.646a.5.5 0 0 0 .708-.707L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5ZM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5 5 5Z"/>
            </svg>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" id="profile" style="color: black;" href="/profile">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" id="logout" style="color: black;" href="/logout">Logout</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" id="show_saved" style="color: black;" href="/show_saved">Saved</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" style="color: black;" href="#" role="button"
                       data-bs-toggle="dropdown "
                       aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>

            </ul>
            <form method="GET" action="{{ url_for('views.search') }}" class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Let's find somthing !" aria-label="Search" name="search" id="search">
                <button class="btn btn-white" type="submit">

                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="Grey"
                         class="bi bi-search-heart" viewBox="0 0 16 16">
                        <path d="M6.5 4.482c1.664-1.673 5.825 1.254 0 5.018-5.825-3.764-1.664-6.69 0-5.018Z"/>
                        <path d="M13 6.5a6.471 6.471 0 0 1-1.258 3.844c.04.03.078.062.115.098l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1.007 1.007 0 0 1-.1-.115h.002A6.5 6.5 0 1 1 13 6.5ZM6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11Z"/>
                    </svg>

                </button>
            </form>

            {% else %}
            <a class="nav-item nav-link" id="login" href="/login" style="color: black;">Login</a>
            <a class="nav-item nav-link" id="signup" href="/signup" style="color: black;">Sign Up</a>
            {% endif %}

        </div>
    </div>
</nav>

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
{% if category == 'error' %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% else %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}
{% endfor %}
{% endif %}
{% endwith %}


<div class="container">{% block content %}{% endblock %}</div>
<script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
></script>
<script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
></script>
<script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.0/js/bootstrap.min.js"></script>


<script
        type="text/javascript"
        src="{{ url_for('static', filename='index.js') }}"
></script>
</body>
</html>

app/templates/home.html
{% extends "base.html" %}
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
{% block title %}Home{% endblock %}

{% block content %}
<br>

<br>
<form method="POST" action="{{ url_for('views.add_post') }}">
    <div class="form-group">
        <input
                type="text"
                class="form-control"
                id="post" name="post"
                placeholder="New post, start tapping here...">
    </div>
    <br>
    <div class="text-center">

        <button
                type="submit"
                class="btn btn-white">
            <svg
                    xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="black"
                    class="bi bi-cursor" viewBox="0 0 16 16">
                <path
                        d="M14.082 2.182a.5.5 0 0 1 .103.557L8.528 15.467a.5.5 0 0 1-.917-.007L5.57 10.694.803 8.652a.5.5 0 0 1-.006-.916l12.728-5.657a.5.5 0 0 1 .556.103zM2.25 8.184l3.897 1.67a.5.5 0 0 1 .262.263l1.67 3.897L12.743 3.52 2.25 8.184z"
                />
            </svg>
        </button>

    </div>
</form>
<br>
<h1 align="center"></h1>
<div id="posts">
    {% for post in posts %}
    <div class="card border-dark">
        <div class="card-footer text-muted">
            <a href="/user_posts/{{post.user.username}}" style="color: black">{{post.user.username}}</a>
        </div>
        <div class="card-header d-flex justify-content-between align-items-center">
            <div><small><small><small>{{post.date.strftime('%d.%m.%y')}}</small></small></small></div>

            {% if current_user.id == post.author %}
            <div class="btn-group">
                <a href="/delete_post/{{post.id}}" class="dropdown-item">Delete</a>
            </div>
            {% endif %}
        </div>

        {% if post in user.saved %}
        <div class="btn-group" style="position: absolute; bottom: 0; height: 65px; line-height: 65px;">
            <a href="/saved/{{post.id}}" class="dropdown-item">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red"
                     class="bi bi-bookmark-heart" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M8 4.41c1.387-1.425 4.854 1.07 0 4.277C3.146 5.48 6.613 2.986 8 4.412z"/>
                    <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"/>
                </svg>
            </a>
        </div>

        {% else %}
        <div class="btn-group" style="position: absolute; bottom: 0 ; height: 65px; line-height: 65px;">
            <a href="/saved/{{post.id}}" class="dropdown-item">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="black"
                     class="bi bi-bookmark-heart" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M8 4.41c1.387-1.425 4.854 1.07 0 4.277C3.146 5.48 6.613 2.986 8 4.412z"/>
                    <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"/>
                </svg>
            </a>
        </div>

        {% endif %}

        <center>
            <div class="card-body">
                {% if current_user.id == post.author %}
                {% if post.edit %}

                <form class="ui form" action="/edit_post/{{post.id}}" method="POST">

                    <input
                            type="text"
                            class="form-control post"
                            name="post"
                            value="{{post.post}}">

                    <button type="submit" class="btn btn-sm btn-white">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-check-lg" viewBox="0 0 16 16">
                            <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z"/>
                        </svg>
                    </button>

                </form>

                {% else %}

                <div class="card-text">{{post.post}}</div>

                <form class="ui form" action="/edit/{{post.id}}" method="POST">
                    <button type="submit" class="btn btn-sm btn-white"
                            style="position: absolute; right: 0; top: 75%; transform: translateY(-50%);">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-pen"
                             viewBox="0 0 16 16">
                            <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
                        </svg>
                    </button>
                </form>

                {% endif %}
                {% else %}
                <div class="card-text">{{post.post}}</div>
                {% endif %}

                <br>


                {{ post.likes | length }} {% if user.id in post.likes | map(attribute="author") | list %}

                <div class="btn-group" style="position: absolute; bottom: 0; height: 65px; line-height: 65px;">
                    <a href="/like_post/{{post.id}}" class="dropdown-item">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red"
                             class="bi bi-suit-heart-fill" viewBox="0 0 16 16">
                            <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
                        </svg>
                    </a>
                </div>

                {% else %}
                <div class="btn-group" style="position: absolute; bottom: 0; height: 65px; line-height: 65px;">
                    <a href="/like_post/{{post.id}}" class="dropdown-item">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="black"
                             class="bi bi-suit-heart" viewBox="0 0 16 16">
                            <path d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"/>
                        </svg>
                    </a>
                </div>


                {% endif %}

            </div>
        </center>
    </div>

    <form method="POST" action="/add_comment/{{post.id}}">
        <div class="form-control border-top" style="position: relative; border: 1px solid black;">
            <div class="form-group">
                {% if post.comments|length > 0 %}
                <button type="button" class="btn btn-white" data-toggle="collapse"
                        data-target="#commentSection{{post.id}}">
                    View {{post.comments|length}} comments
                </button>
                <div id="commentSection{{post.id}}" class="collapse">
                    <br>

                    {% for comment in comments %}
                    <div class="form-control" style="position: relative;">
                        {{ user.username }}
                        <br>
                        <small><small><small>{{ comment.date.strftime('%d.%m.%y') }}</small></small></small>

                        {% if current_user.id == comment.author %}
                        <div class="btn-group" style="float: right;">
                            <a href="/delete_comment/{{comment.id}}/{{post.id}}" class="dropdown-item">Delete</a>
                        </div>
                        {% endif %}
    </form>
    <hr>

    {% if current_user.id == comment.author %}
    {% if comment.edit_switch %}

    <form class="ui form" action="/edit_comment/{{comment.id}}" method="POST">

        <input
                type="text"
                class="form-control comment"
                name="comment"
                value="{{comment.comment}}">

        <button type="submit" class="btn btn-sm btn-white">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                 class="bi bi-check-lg" viewBox="0 0 16 16">
                <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z"/>
            </svg>
        </button>

    </form>

    {% else %}

    <div class="card-text">{{comment.comment}}</div>

    <form class="ui form" action="/edit_switch/{{comment.id}}" method="POST">
        <button type="submit" class="btn btn-sm btn-white"
                style="position: absolute; right: 0; top: 75%; transform: translateY(-50%);">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                 class="bi bi-pen"
                 viewBox="0 0 16 16">
                <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
            </svg>
        </button>
    </form>

    {% endif %}
    {% else %}
    <div class="card-text">{{comment.comment}}</div>
    {% endif %}


    <br>
    <br>
</div>
<br>
{% endfor %}
</div>
{% endif %}
</div>

<div style="position: relative">
    <input
            type="text"
            class="form-control"
            id="comment"
            name="comment"
            placeholder="New comment, start tapping here..."
    />
    <button
            type="submit"
            class="btn btn-white"
            style="position: absolute; right: 0; top: 50%; transform: translateY(-50%);">
        <svg
                xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="black"
                class="bi bi-cursor" viewBox="0 0 16 16">
            <path
                    d="M14.082 2.182a.5.5 0 0 1 .103.557L8.528 15.467a.5.5 0 0 1-.917-.007L5.57 10.694.803 8.652a.5.5 0 0 1-.006-.916l12.728-5.657a.5.5 0 0 1 .556.103zM2.25 8.184l3.897 1.67a.5.5 0 0 1 .262.263l1.67 3.897L12.743 3.52 2.25 8.184z"
            />
        </svg>
    </button>
</div>
</div>


<br>
{% endfor %}

{% endblock %}
</div>

app/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}


{% block content%}

<form method="POST">
    <h3 align="center">LOGIN</h3>
    <div class="form-group">
        <label for="email">Email</label>
        <input
                class="form-control"
                type="email"
                id="email"
                name="email"
                placeholder="Enter your email here"
        />
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input
                class="form-control"
                type="password"
                id="password"
                name="password"
                placeholder="Enter your password here"
        />
    </div>
    <br>
    <button type=submit class="btn btn-primary">Submit</button>
</form>

{% endblock %}

app/templates/signup.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content%}

<form method="POST">
    <h3 align="center">SIGN UP</h3>
    <div class="form-group">
        <label for="email">Email</label>
        <input
                class="form-control"
                type="email"
                id="email"
                name="email"
                placeholder="Enter your email here"
        />
    </div>
    <div class="form-group">
        <label for="first_name">First name</label>
        <input
                class="form-control"
                type="text"
                id="first_name"
                name="first_name"
                placeholder="Enter your first_name here"
        />
    </div>
    <div class="form-group">
        <label for="username">Username</label>
        <input
                class="form-control"
                type="text"
                id="username"
                name="username"
                placeholder="Enter your username here"
        />
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input
                class="form-control"
                type="password"
                id="password"
                name="password"
                placeholder="Enter your password here"
        />
    </div>
    <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input
                class="form-control"
                type="password"
                id="password2"
                name="password2"
                placeholder="Enter your password again"
        />
    </div>
    <br>
    <button type=submit class="btn btn-primary">Submit</button>
</form>


{% endblock %}